Repository mash-up-kr/devoops-web, pull requests merged in 2025-06, with the labels that each got.

#13 feat: 정적 자원 도메인 추가
  next.config.ts
Labels: ✨ Feature

#15 style: `colors` 및 `typography` 디자인 토큰 정의
  .eslintrc.json
  package.json
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/providers/QueryProvider.tsx
  src/providers/getQueryClient.tsx
  src/styles/colors.css
  src/styles/typography.css
  yarn.lock
Labels: ⚙️ Chore, 🎨 Styles

#18 feat: `Tag` 컴포넌트 제작
  src/app/page.tsx
  src/components/common/Tag/Tag.tsx
Labels: ✨ Feature

#21 feat: GlobalNavigation 컴포넌트 UI 및 레이아웃 구현 및 렌더링
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/Button.tsx
  src/components/common/GlobalNavigation.tsx
  src/components/common/Tabs/index.ts
  src/components/common/Tag.tsx
  src/styles/spacing.css
Labels: ✨ Feature

#22 style: global background css 오류 수정
  src/app/globals.css
  src/components/home/MyPRSection.tsx
  src/components/home/PRItem/PRContent.tsx
  src/components/home/PRItem/PRItem.tsx
  src/components/home/PRItem/PRStatus.tsx
  src/components/home/PRItem/index.ts
Labels: 🎨 Styles, 🐞 Fix

#23 Revert: GSS-91
  src/components/home/MyPRSection.tsx
  src/components/home/PRItem/PRContent.tsx
  src/components/home/PRItem/PRItem.tsx
  src/components/home/PRItem/PRStatus.tsx
  src/components/home/PRItem/index.ts
Labels: 🐞 Fix
