Repository mash-up-kr/devoops-web, pull requests merged in 2025-07, with the labels that each got.

#14 feat: React Portal을 활용해 UI에 종속되지 않는 Headless 모달 구현
  .cz-config.js
  .eslintrc.json
  .yarn/install-state.gz
  src/app/globals.css
  src/app/layout.tsx
  src/app/modal-test/page.tsx
  src/components/modal/ModalContent.tsx
  src/components/modal/ModalContext.tsx
  src/components/modal/ModalRoot.tsx
  src/components/modal/ModalToggle.tsx
  src/components/modal/Portal.tsx
  src/components/modal/index.ts
  src/styles/z-index.css
  src/types/modal.ts
  tsconfig.json
  yarn.lock
Labels: ✨ Feature

#28 feat: 홈 페이지 퍼블리싱
  src/app/page.tsx
  src/assets/svg/add.svg
  src/assets/svg/chevron-left.svg
  src/assets/svg/chevron-right.svg
  src/components/common/Tag.tsx
  src/components/home/AISummary.tsx
  src/components/home/MyPR.tsx
  src/components/home/PRItem/PRContent.tsx
  src/components/home/PRItem/PRItem.tsx
  src/components/home/PRItem/PRStatus.tsx
  src/components/home/PRItem/index.ts
  src/components/home/Preview.tsx
  src/components/home/QuestionPreview.tsx
  src/components/home/QuestionTabs/CategoryCarousel/CategoryCarousel.tsx
  src/components/home/QuestionTabs/CategoryCarousel/CategoryCarouselContent.tsx
  src/components/home/QuestionTabs/CategoryCarousel/CategoryCarouselItem.tsx
  src/components/home/QuestionTabs/CategoryCarousel/CategoryCarouselNavigator.tsx
  src/components/home/QuestionTabs/QuestionContent.tsx
  src/components/home/QuestionTabs/QuestionItem.tsx
  src/components/home/QuestionTabs/QuestionTabs.tsx
  src/components/home/QuestionTabs/index.ts
  src/providers/QuestionTabsContext.tsx
  src/styles/colors.css
  src/types/questionTabs.d.ts
  src/utils/findIndexById.ts
Labels: ✨ Feature

#29 feat: `Profile` 컴포넌트 제작 및 `Modal` 구조 수정
  src/app/layout.tsx
  src/assets/images/avatar.png
  src/assets/svg/close.svg
  src/assets/svg/profile.svg
  src/components/common/GlobalNavigation.tsx
  src/components/common/Modal/ModalContent.tsx
  src/components/common/Modal/ModalRoot.tsx
  src/components/common/Modal/ModalToggle.tsx
  src/components/common/Modal/Portal.tsx
  src/components/common/Modal/ProfileModal/ProfileButton.tsx
  src/components/common/Modal/ProfileModal/ProfileContent.tsx
  src/components/common/Modal/ProfileModal/ProfileModal.tsx
  src/components/common/Modal/ProfileModal/index.ts
  src/components/common/RepositoryBadge.tsx
  src/styles/colors.css
  src/utils/onKeydown.ts
  src/utils/stopPropagation.ts
Labels: ✨ Feature, 🛠️ Refactor

#30 Feat: 레포연동 퍼블리싱
  mashup.config.ts
  package.json
  src/__generated__/@http-client/index.ts
  src/__generated__/@types/index.ts
  src/__generated__/Api/Api.api.ts
  src/app/(with-layout)/layout.tsx
  src/app/(with-layout)/page.tsx
  src/app/(with-layout)/retrospective/[pullRequestId]/layout.tsx
  src/app/(with-layout)/retrospective/[pullRequestId]/page.tsx
  src/app/layout.tsx
  src/app/repolink/page.tsx
  src/components/repolink/Repolink.tsx
  yarn.lock
Labels: ✨ Feature, 🎨 Styles

#32 feat: 초기홈 퍼블리싱
  src/app/(with-layout)/layout.tsx
  src/app/landing/page.tsx
  src/app/layout.tsx
  src/components/landing/Landing.tsx
Labels: 🎨 Styles

#27 feat: 회고 상세 페이지 API 연동
  src/__generated__/Api/Api.api.ts
  src/apis/pull-requests/retrospective.mutate.ts
  src/apis/pull-requests/retrospective.query.ts
  src/apis/question/answer.mutate.ts
  src/apis/question/answer.query.ts
  src/app/(with-layout)/retrospective/[pullRequestId]/page.tsx
  src/app/api/pull-requests/[pullRequestId]/done/route.ts
  src/components/retrospective/FixedFooter.tsx
  src/components/retrospective/PullRequestSummary.tsx
  src/components/retrospective/RetrospectiveAnswers.tsx
  src/components/retrospective/RetrospectiveHeader.tsx
  src/components/retrospective/RetrospectiveQuestions.tsx
  src/hooks/api/retrospective/useCreateAnswerMutation.ts
  src/hooks/api/retrospective/useDeleteAnswerMutation.ts
  src/hooks/api/retrospective/usePullRequestDetail.ts
  src/hooks/api/retrospective/useUpdateAllAnswersMutation.ts
  src/hooks/api/retrospective/useUpdateAnswerMutation.ts
  src/types/retrospective.ts
  yarn.lock
Labels: ✨ Feature, 🌐 API

#40 feat: 홈 일부 미구현 사항 반영
  src/actions/token.action.ts
  src/app/(with-layout)/page.tsx
  src/assets/svg/logo.svg
  src/components/common/GlobalNavigation.tsx
  src/components/common/Modal/ProfileModal/ProfileContent.tsx
  src/components/common/Modal/RepolinkModal/RepolinkModal.tsx
  src/components/home/MyPR.tsx
  src/components/home/QuestionTabs/CategoryCarousel/CategoryCarouselItem.tsx
  src/components/home/QuestionTabs/QuestionContent.tsx
  src/components/home/QuestionTabs/QuestionTabs.tsx
  src/components/repolink/Repolink.tsx
  src/styles/colors.css
Labels: ⚙️ Chore, ✨ Feature, 🛠️ Refactor

#44 chore: 미 구현사항 처리
  src/apis/repositories/repositories.query.ts
  src/app/(with-layout)/error.tsx
  src/app/(with-layout)/page.tsx
  src/app/error.tsx
  src/assets/images/avatar.png
  src/assets/images/avatar.webp
  src/assets/images/status-view.webp
  src/components/common/Modal/ProfileModal/ProfileContent.tsx
  src/components/common/Modal/RepolinkModal/RepolinkModal.tsx
  src/components/common/RepositoryBadge.tsx
  src/components/common/StatusView/EmptyListView.tsx
  src/components/common/StatusView/ErrorView.tsx
  src/components/common/StatusView/StatusView.tsx
  src/components/common/Tag.tsx
  src/components/home/MyPR.tsx
  src/components/home/PRItem/PRContent.tsx
  src/components/home/PRPreview.tsx
  src/components/home/Preview.tsx
  src/components/home/RepositoryList.tsx
  src/styles/colors.css
  src/utils/getTagColor.ts
Labels: ⚙️ Chore, ✨ Feature, 🛠️ Refactor

#49 fix: 빌드 에러 해결
  src/app/auth/github/callback/page.tsx
  src/components/landing/Landing.tsx
Labels: 🐞 Fix

#50 fix: 빌드 에러 해결
  src/app/auth/github/callback/page.tsx
  src/components/landing/Landing.tsx
Labels: 🐞 Fix

#51 feat: 랜딩 페이지 제작
  next.config.ts
  src/app/landing/page.tsx
  src/assets/images/landing/landing-hero.webp
  src/assets/images/landing/landing-pr-summary.webp
  src/assets/images/landing/landing-repolink.webp
  src/assets/images/landing/landing-retrospective-answer.webp
  src/assets/images/landing/landing-retrospective-question.webp
  src/assets/images/landing/landing-symbol-1.webp
  src/assets/images/landing/landing-symbol-2.webp
  src/assets/images/landing/landing-symbol-3.webp
  src/assets/svg/feature-card-gradient.svg
  src/components/common/Tabs/TabsTrigger.tsx
  src/components/common/Tag.tsx
  src/components/landing/FeatureCard.tsx
  src/components/landing/GradientBottomLayer.tsx
  src/components/landing/GradientTopLayer.tsx
  src/components/landing/Landing.tsx
  src/components/landing/LandingNavigation.tsx
  src/components/landing/Section/FeatureSection.tsx
  src/components/landing/Section/FooterCTA.tsx
  src/components/landing/Section/HeroSection.tsx
  src/components/landing/Section/RepolinkSection.tsx
  src/components/landing/Section/StartSection.tsx
  src/hooks/useLoginRedirect.ts
  src/styles/colors.css
  src/styles/z-index.css
Labels: ✨ Feature

#56 fix: 페이지네이션 백엔드 명세에 맞게 수정
  src/components/home/RepositoryList.tsx
  src/components/landing/Section/FeatureSection.tsx
Labels: ⚙️ Chore, 🐞 Fix

#57 fix: 페이지네이션 백엔드 명세에 맞게 수정
  src/components/home/RepositoryList.tsx
  src/components/landing/Section/FeatureSection.tsx
Labels: ⚙️ Chore, 🐞 Fix

#64 docs: `README.md` 수정
  README.md
Labels: 📝 Docs

#65 docs: README.md 수정
  README.md
Labels: 📝 Docs

#66 docs: 이슈 템플릿 제작 및 적용
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: 📝 Docs

#68 docs: 이슈 템플릿 불필요한 부분 주석처리
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: ⚙️ Chore, 📝 Docs

#69 docs: 이슈 템플릿 불필요한 부분 주석처리
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: ⚙️ Chore, 🐞 Fix
