Repository mash-up-kr/devoops-web, pull requests merged in 2025-09, with the labels that each got.

#132 style: 레포지토리 추가 모달에 대한 UT 사항 반영
  src/components/common/Modal/RepolinkModal/RepolinkModal.tsx
Labels: 🎨 Styles

#141 style: 랜딩 페이지 반응형 디자인 반영
  src/components/common/Tag.tsx
  src/components/landing/FeatureCard.tsx
  src/components/landing/Gradient/GradientBottomLayer.tsx
  src/components/landing/Gradient/GradientTopLayer.tsx
  src/components/landing/Gradient/GradientWrapper.tsx
  src/components/landing/GradientBottomLayer.tsx
  src/components/landing/Landing.tsx
  src/components/landing/Section/FeatureSection.tsx
  src/components/landing/Section/FooterCTA.tsx
  src/components/landing/Section/HeroSection.tsx
  src/components/landing/Section/RepolinkSection.tsx
  src/components/landing/Section/StartSection.tsx
  src/styles/spacing.css
  src/styles/typography.css
Labels: ✨ Feature, 🎨 Styles

#144 chore: 회고 질문 텍스트 오버플로우로 인한 레이아웃 깨짐 현상 해결 해결
  src/components/retrospective/RetrospectiveAnswers.tsx
  src/components/retrospective/RetrospectiveQuestions.tsx
Labels: ⚙️ Chore, 🛠️ Refactor
