Repository mash-up-kr/devoops-web, pull requests merged in 2025-08, with the labels that each got.

#71 refactor: 로그아웃 후 재로그인시 계정을 선택할 수 있도록 수정
  README.md
  src/app/auth/github/callback/page.tsx
  src/app/auth/github/page.tsx
  src/components/auth/GithubCallback.tsx
  src/components/landing/Section/HeroSection.tsx
Labels: ⚙️ Chore, 🛠️ Refactor

#77 refactor: 회고 완료 버튼 두 번 이상 클릭 시 회고 박스가 사라지는 이슈 해결
  src/app/(with-layout)/retrospective/[pullRequestId]/page.tsx
  src/app/auth/github/callback/page.tsx
  src/components/retrospective/FixedFooter.tsx
Labels: 🐞 Fix

#78 deploy: 8월 1주차 스프린트 반영
  README.md
  next.config.ts
  package.json
  public/assets/images/opengraph-image.webp
  src/app/(with-layout)/retrospective/[pullRequestId]/page.tsx
  src/app/auth/github/callback/page.tsx
  src/app/auth/github/page.tsx
  src/app/layout.tsx
  src/components/auth/GithubCallback.tsx
  src/components/common/GoogleAnalytics.tsx
  src/components/home/PRItem/PRItem.tsx
  src/components/home/QuestionTabs/QuestionContent.tsx
  src/components/home/RepositoryList.tsx
  src/components/landing/Section/HeroSection.tsx
  src/components/retrospective/FixedFooter.tsx
  src/constants/routes.ts
  yarn.lock
Labels: 🌎 Deploy

#88 feat: Tracking 여부에 따른 레포지토리 상태 구별하기
  src/__generated__/@types/index.ts
  src/components/common/Modal/RepolinkModal/RepolinkModal.tsx
Labels: ✨ Feature

#90 chore: main과 develop 상태 일치화
  src/components/home/QuestionTabs/CategoryCarousel/CategoryCarousel.tsx
  src/components/home/QuestionTabs/QuestionTabs.tsx
Labels: ⚙️ Chore

#95 feat: MSW 세팅 및 일부 mock api 제작
  .eslintrc.json
  package.json
  public/mockServiceWorker.js
  src/apis/github/github.api.ts
  src/app/layout.tsx
  src/constants/domain.ts
  src/constants/routes.ts
  src/middleware.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/handlers/repositoriesHandler.ts
  src/mocks/handlers/userHandler.ts
  src/mocks/index.ts
  src/mocks/responses/repositories/getEntirePullRequests.json
  src/mocks/responses/repositories/getPullRequest.json
  src/mocks/responses/repositories/getRepositoriesMe.json
  src/mocks/responses/repositories/getRepositoryPullRequests.json
  src/mocks/responses/user/getMyInfo.json
  src/mocks/server.ts
  src/providers/MSWClientProvider.tsx
  tsconfig.json
  yarn.lock
Labels: ✨ Feature, 🌐 API, 💾 Env

#97 refactor: 이전에 선택한 카테고리가 유지될 수 있도록 한다
  src/apis/index.ts
  src/components/home/MyPR.tsx
  src/components/home/Overview.tsx
  src/components/home/Preview.tsx
  src/components/home/QuestionPreview.tsx
  src/components/home/QuestionTabs/QuestionTabs.tsx
  src/hooks/home/usePagination.ts
Labels: 🛠️ Refactor

#105 fix: 배포 중 발생하는 이슈 해결
  .eslintrc.json
  src/apis/index.ts
  src/components/common/Modal/RepoLoadingModal/RepoLoadingModal.tsx
  src/components/home/MyPR.tsx
  src/components/home/Overview.tsx
  src/constants/modal.ts
Labels: 🐞 Fix

#108 refactor: instrumentation에 msw 서버 환경 설정 로직 추가
  src/app/(with-layout)/page.tsx
  src/app/layout.tsx
  src/instrumentation.ts
  src/mocks/index.ts
  src/providers/MSWClientProvider.tsx
Labels: 🛠️ Refactor

#113 refactor: Github Not Found가 날 때 특정 링크로 리다이렉트 할 수 있도록 한다
  src/components/common/Modal/RepolinkModal/RepolinkModal.tsx
  src/constants/domain.ts
  src/mocks/handlers/repositoriesHandler.ts
  src/mocks/responses/repositories/saveRepository/notFound.json
  src/mocks/responses/repositories/saveRepository/success.json
Labels: 🛠️ Refactor

#115 feat: 회고 답변 입력에 마크다운 에디터 기능 추가
  .eslintrc.json
  package.json
  postcss.config.mjs
  public/mockServiceWorker.js
  src/app/globals.css
  src/components/retrospective/AnswerEditor.tsx
  src/components/retrospective/RetrospectiveAnswers.tsx
  yarn.lock
Labels: ✨ Feature
